server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: citse-ms-maestra
          uri: lb://citse-ms-maestra
          predicates:
            - Path=/maestra/**
          filters:
            - StripPrefix=1

        - id: citse-ms-tipo
          uri: lb://citse-ms-tipo
          predicates:
            - Path=/tipo/**
          filters:
            - StripPrefix=1

        - id: citse-ms-cuestionario
          uri: lb://citse-ms-cuestionario
          predicates:
            - Path=/cuestionario/**
          filters:
            - StripPrefix=1

        - id: citse-ms-ubigeo
          uri: lb://citse-ms-ubigeo
          predicates:
            - Path=/ubigeo/**
          filters:
            - StripPrefix=1

        - id: citse-ms-entidad
          uri: lb://citse-ms-entidad
          predicates:
            - Path=/entidades/**
          filters:
            - StripPrefix=1

        - id: citse-ms-negocio
          uri: lb://citse-ms-negocio
          predicates:
            - Path=/negocio/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enable: true
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTION
