server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: citse-ms-maestra
          uri: lb://maestra-service
          predicates:
            - Path=/maestra/**
          filters:
            - StripPrefix=1

        - id: citse-ms-tipo
          uri: lb://tipo-service
          predicates:
            - Path=/tipo/**
          filters:
            - StripPrefix=1

        - id: citse-ms-cuestionario
          uri: lb://cuestionario-service
          predicates:
            - Path=/cuestionario/**
          filters:
            - StripPrefix=1
            
      discovery:
        locator:
          enable: true
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTION
