server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: maestra-service
          uri: lb://maestra-service
          predicates:
            - Path=/maestra/**
          filters:
            - StripPrefix=1

        - id: negocio-service
          uri: lb://negocio-service
          predicates:
            - Path=/negocio/**

        - id: tipo-service
          uri: lb://tipo-service
          predicates:
            - Path=/tipo/**

        - id: ubigeo-service
          uri: lb://ubigeo-service
          predicates:
            - Path=/ubigeo/**
      discovery:
        locator:
          enable: true
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTION
